#!/bin/sh

if [ $# -ne 2 ]
then
    echo "run-datagram-crusher <bind-address:port> <connect-address:port>"
    exit 1
fi

mvn \
    --offline \
    --quiet \
    exec:java \
    -P exec-java \
    -Dorg.slf4j.simplelogger.defaultlog=info \
    -Dorg.slf4j.simplelogger.showdatetime=true \
    -Dorg.slf4j.simplelogger.showthreadname=false \
    -Dorg.slf4j.simplelogger.showlogname=false \
    -Dexec.mainClass=org.netcrusher.datagram.DatagramCrusherMain \
    -Dexec.args="$1 $2"