#!/bin/sh

if [ $# -ne 2 ]
then
    echo "run-tcp-crusher <bind-address:port> <connect-address:port>"
    exit 1
fi

mvn \
    --offline \
    --quiet \
    exec:java \
    -Dlogback.configurationFile=logback-run.xml \
    -Dexec.classpathScope=test \
    -Dexec.mainClass=org.netcrusher.tcp.main.TcpCrusherMain \
    -Dexec.args="$1 $2"